### ISSUE TITLE
py3: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by josephholsten** [aquach/vim-mediawiki-editor#12]
## Platform

* macOS: 10.12.6 (16G29)
* brew:neovim: 0.2.0
* brew:python3: 3.6.2
* pip3:mwclient: 0.8.6
* pip3:neovim: 0.1.13

<details>

```
$ uname -a
Darwin Isha.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

$ nvim --version
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"

$ python3 --version
Python 3.6.2

$ pip3 show neovim
Name: neovim
Version: 0.1.13
Summary: Python client to neovim
Home-page: http://github.com/neovim/python-client
Author: Thiago de Arruda
Author-email: tpadilha84@gmail.com
License: Apache
Location: /usr/local/lib/python3.6/site-packages
Requires: msgpack-python, greenlet

$ pip3 show mwclient
Name: mwclient
Version: 0.8.6
Summary: MediaWiki API client
Home-page: https://github.com/btongminh/mwclient
Author: Bryan Tong Minh
Author-email: bryan.tongminh@gmail.com
License: MIT
Location: /usr/local/lib/python3.6/site-packages
Requires: six, requests-oauthlib
```
</details>

## What I did

```
:MWRead A
```

## What I expected

For the Wikipedia article https://en.wikipedia.org/wiki/A to be loaded into the current buffer

## What actually happened

```
Error detected while processing function <SNR>49_MWRead[2]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$HOME/.config/nvim/plugged/vim-mediawiki-editor/plugin/mediawiki_editor.py", line 129, in mw_read
    article_name = article_name.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by josephholsten** [comment]
NB:
```
$ python3
>>> "abc".decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'decode'

$ python2
>>> "abc".decode('utf-8')
u'abc'
```

**Comment by josephholsten** [comment]
https://stackoverflow.com/questions/14472650/python-3-encode-decode-vs-bytes-str

Seems to indicate that the solution is to always `article_name.encode('utf-8').decode('utf-8')`. This seems insane.

Instead, my local copy simply has the `.decode('utf-8')` removed. Seems to be working fine.

**Comment by saurabh8290** [comment]
import numpy as np
from keras.models import load_model
from keras.preprocessing import image
test_image = image.load_img('E:/images/vikram/vi.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
model = load_model('friend.h5')
result = model.predict(test_image)
print(result)





**and i got this error:

AttributeError                            Traceback (most recent call last)
<ipython-input-1-174a54b9676a> in <module>
      5 test_image = image.img_to_array(test_image)
      6 test_image = np.expand_dims(test_image, axis = 0)
----> 7 model = load_model('friend.h5')
      8 result = model.predict(test_image)
      9 print(result)

c:\users\sa251\anaconda3\envs\dogcat_test\lib\site-packages\keras\engine\saving.py in load_wrapper(*args, **kwargs)
    490                 os.remove(tmp_filepath)
    491             return res
--> 492         return load_function(*args, **kwargs)
    493 
    494     return load_wrapper

c:\users\sa251\anaconda3\envs\dogcat_test\lib\site-packages\keras\engine\saving.py in load_model(filepath, custom_objects, compile)
    582     if H5Dict.is_supported_type(filepath):
    583         with H5Dict(filepath, mode='r') as h5dict:
--> 584             model = _deserialize_model(h5dict, custom_objects, compile)
    585     elif hasattr(filepath, 'write') and callable(filepath.write):
    586         def load_function(h5file):

c:\users\sa251\anaconda3\envs\dogcat_test\lib\site-packages\keras\engine\saving.py in _deserialize_model(h5dict, custom_objects, compile)
    271     if model_config is None:
    272         raise ValueError('No model found in config.')
--> 273     model_config = json.loads(model_config.decode('utf-8'))
    274     model = model_from_config(model_config, custom_objects=custom_objects)
    275     model_weights_group = h5dict['model_weights']

AttributeError: 'str' object has no attribute 'decode**'


can you suggest me the solution..Thank you!
