### ISSUE TITLE
'mw_read' is not defined

### ISSUE THREAD

**Issue by mattiasJohnson** [aquach/vim-mediawiki-editor#14]
I've installed vim-mediawiki-editor with vim-Plug (and vim-Plug tells me the installation is OK) and installed mwclient with pip. When I try to run a command I get this error:

`Error detected while processing function <SNR>14_MWRead:
line      2:
Traceback (most recent call last):
   File "<string>", line 1, in <module>
NameError: name 'mw_read' is not defined`

One guess from me is that I need to set all the variables such as g:mediawiki_editor_url since I'm not getting any prompt, if this is the solution then my follow-up question is where do I change them?

Thanks in advance

**Comment by aquach** [comment]
Is your vim compiled with python? In Vim, can you `:echo has('python')` and see if it says 1 or 0?

**Comment by aquach** [comment]
Have you also tried restarting your vim? Or try `:python import mwclient` to see if you get an error?

**Comment by mattiasJohnson** [comment]
No I haven't got python with my vim only python3, so I guess finding a vim version with python should solve the problem?

I don't know if this helps (I'm quite new to linux as you might can tell) but running your command with python3 instead gives me: ModuleNotFoundError: No module named 'mwclient'

**Comment by aquach** [comment]
Ah, so that means your Vim is trying to use Python 3, but you only installed mwclient on Python 2. So maybe try `pip3 install mwclient`?

**Comment by mattiasJohnson** [comment]
I've now successfully installed `mwclient` with `pip3`.  When I try a command e.g: `MWRead articlename` I get:

```
Error detected while processing function <SNR>14_MWRead:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mattias/.vim/plugged/vim-mediawiki-editor/plugin/mediawiki_editor.py", line 129, in mw_read
    article_name = article_name.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

P.S I still haven't set all my variables such as `g:mediawiki_editor_url`, maybe setting them manually could help? If so then where do I set them?

**Comment by aquach** [comment]
Mm, that looks like a change between Python2 and Python3. The plugin may only work with Python2. If you can get vim to have Python2 rather than Python3, it should probably work better. Sorry I don't have a better solution for you!

**Comment by mattiasJohnson** [comment]
Okay I'll try to get vim with Python2 then. No worries, thank you for taking the time to help me identify the problem!
