### ISSUE TITLE
`g:mediawiki_editor_uri_scheme` is undocumented

### ISSUE THREAD

**Issue by Jeremiah-England** [aquach/vim-mediawiki-editor#21]
Hi and thanks for making this plugin!

I'm pretty new to plugins and vim (...had to look up how to set vim variables), so the fact that I was able to figure this out probably means it's not a big deal. But it was confusing for a bit.

I have MediaWiki on my local raspberry pi and the uri scheme must be `http`, otherwise `mwclient.Site()` throws a `ConnectionRefused` error.

So I added `let g:mediawiki_editor_uri_scheme = 'http'` to my `~/vimrc` file and it works fine now.

**Comment by aquach** [comment]
Thanks for reporting! Fixed :)
